<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Marten" Version="9.29.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.10" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsuranceUnderwriting.Application\InsuranceUnderwriting.Application.csproj" />
    <ProjectReference Include="..\InsuranceUnderwriting.Infrastructure\InsuranceUnderwriting.Infrastructure.csproj" />
    <ProjectReference Include="..\InsuranceUnderwriting.Domain\InsuranceUnderwriting.Domain.csproj" />
  </ItemGroup>

</Project>
